apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: microservices-photogallery
build:
  local:
    push: false
  artifacts:
    - image: ranamahadahmer/eventbus
      context: MicroServices/EventBusServ
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: ranamahadahmer/frontend
      context: MicroServices/GalleryMgmtServ
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: ranamahadahmer/gallerymgmt
      context: MicroServices/QueryServ
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: ranamahadahmer/logging
      context: MicroServices/StorageMgmtServ
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: ranamahadahmer/query
      context: MicroServices/EventBusServ
      docker:
        dockerfile: Dockerfile
    - image: ranamahadahmer/storagemgmt
      context: MicroServices/UsageMntrServ
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: ranamahadahmer/usagemntr
      context: MicroServices/UserAccMgmtServ
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: ranamahadahmer/useraccmgmt
      context: MicroServices/loggingServ
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
manifests:
  rawYaml:
    - k8s/eventbus-depl.yaml
    - k8s/frontend-depl.yaml
    - k8s/gallerymgmt-depl.yaml
    - k8s/ingress-serv.yaml
    - k8s/logging-depl.yaml
    - k8s/query-depl.yaml
    - k8s/storagemgmt-depl.yaml
    - k8s/usagemntr-depl.yaml
    - k8s/useraccmgmt-depl.yaml
